spring:
  application:
    name: blog-back

  profiles:
    active: dev  # 默认使用 dev 配置
  datasource:
    url: jdbc:mysql://${production.datasource.domain}:${production.datasource.port}/${production.datasource.database}?useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&characterEncoding=utf8
    username: ${production.datasource.username}
    password: ${production.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  data:
    redis:
      host: ${production.data.redis.host}
      port: ${production.data.redis.port}
      password: ${production.data.redis.password}
      database: 8

  mail:
    host: ${production.mail.host}
    username: ${production.mail.username}
    # 显示在发件人上的名称(这个是自定义的字段,spring不会读取)
    from-name: ${production.mail.from-name}
    password: ${production.mail.password}
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

# mybatis 公共配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# OSS 公共配置，占位引用 dev
oss:
  endpoint: ${production.oss.endpoint}
  bucket-name: ${production.oss.bucket-name}
  region: ${production.oss.region}
  oss-access-key-id: ${production.oss.oss-access-key-id}
  oss-access-key-secret: ${production.oss.oss-access-key-secret}

knife4j:
  enable: false
  setting:
    language: zh_cn
server:
  port: 8080

