spring:
  application:
    name: blog-back

  profiles:
    active: dev  # 默认使用 dev 配置

  datasource:
    url: ${production.datasource.url}
    username: ${production.datasource.username}
    password: ${production.datasource.password}
    driver-class-name: ${production.datasource.driver-class-name}

  servlet:
    multipart:
      max-file-size: ${production.servlet.multipart.max-file-size}
      max-request-size: ${production.servlet.multipart.max-request-size}

# mybatis 公共配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# OSS 公共配置，占位引用 dev
blog:
  oss:
    endpoint: ${production.oss.endpoint}
    bucket-name: ${production.oss.bucket-name}
    region: ${production.oss.region}
    oss-access-key-id: ${production.oss.oss-access-key-id}
    oss-access-key-secret: ${production.oss.oss-access-key-secret}

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '默认'
      paths-to-match: '/**'
      packages-to-scan: com.qiyuan.controller
