spring:
  application:
    name: blog-back

  profiles:
    active: dev  # 默认使用 dev 配置
  datasource:
    url: ${production.datasource.url}
    username: ${production.datasource.username}
    password: ${production.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ${production.data.redis.password}
      database: 8

# mybatis 公共配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# OSS 公共配置，占位引用 dev
blog:
  oss:
    endpoint: ${production.oss.endpoint}
    bucket-name: ${production.oss.bucket-name}
    region: ${production.oss.region}
    oss-access-key-id: ${production.oss.oss-access-key-id}
    oss-access-key-secret: ${production.oss.oss-access-key-secret}

knife4j:
  enable: false
  setting:
    language: zh_cn
server:
  port: 8080

